---
- name: BIG-IP SETUP
  hosts: all
  gather_facts: false

  tasks:
    - name: CREATE NODES
      f5networks.f5_modules.bigip_node:
        provider:
          server: "{{private_ip}}"
          user: "{{f5_user}}"
          password: "{{f5_password}}"
          server_port: 8443
          validate_certs: false
        host: "{{hostvars[item].ansible_host}}"
        name: "{{hostvars[item].inventory_hostname}}"
      loop: "{{ groups['web'] }}"
